// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Palantir.Infrastructure.Persistence;

#nullable disable

namespace Palantir.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PalantirDbContext))]
    [Migration("20260716174452_AddLocalPilotCredentials")]
    partial class AddLocalPilotCredentials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.17");

            modelBuilder.Entity("Palantir.Domain.Entities.ApprovalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset?>("CompletedAt");

                    b.Property<Guid?>("CompletedByUserId");

                    b.Property<Guid?>("DraftId");

                    b.Property<int?>("DraftRevision");

                    b.Property<DateTimeOffset?>("ExpiresAt");

                    b.Property<DateTimeOffset>("RequestedAt");

                    b.Property<Guid>("RequestedForUserId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CompletedByUserId");

                    b.HasIndex("DraftId");

                    b.HasIndex("RequestedForUserId");

                    b.ToTable("ApprovalRequests", (string)null);
                });

            modelBuilder.Entity("Palantir.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ActorUserId");

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<string>("DetailsJson");

                    b.Property<Guid?>("EntityId");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100);

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<Guid>("OrganizationId");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("Palantir.Domain.Entities.ConnectedAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConnectionStatus")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<string>("DisplayName");

                    b.Property<string>("GrantedScopesJson");

                    b.Property<DateTimeOffset?>("LastSuccessfulSyncAt");

                    b.Property<string>("PrimaryAddress");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("ProviderAccountId")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("ProviderTenantId");

                    b.Property<DateTimeOffset>("UpdatedAt");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ConnectedAccounts", (string)null);
                });

            modelBuilder.Entity("Palantir.Domain.Entities.Connector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CapabilitiesJson")
                        .IsRequired();

                    b.Property<string>("ConnectorType")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<Guid?>("DeviceId");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<Guid>("OrganizationId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Connectors", (string)null);
                });

            modelBuilder.Entity("Palantir.Domain.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CustomerId");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<string>("Email")
                        .HasMaxLength(320);

                    b.Property<string>("MetadataJson");

                    b.Property<Guid>("OrganizationId");

                    b.Property<string>("Phone")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Contacts", (string)null);
                });

            modelBuilder.Entity("Palantir.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AssignedTeamId");

                    b.Property<Guid?>("AssignedUserId");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<Guid?>("CustomerId");

                    b.Property<Guid>("OrganizationId");

                    b.Property<Guid?>("ProjectId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Subject")
                        .HasMaxLength(500);

                    b.Property<DateTimeOffset>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTeamId");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Conversations", (string)null);
                });

            modelBuilder.Entity("Palantir.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MetadataJson");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<Guid>("OrganizationId");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("Palantir.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<bool>("IsActive");

                    b.Property<DateTimeOffset?>("LastSeenAt");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("PushToken");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("Palantir.Domain.Entities.Draft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Body")
                        .IsRequired();

                    b.Property<Guid>("ConversationId");

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<bool>("CreatedByAi");

                    b.Property<Guid?>("CreatedByUserId");

                    b.Property<string>("MetadataJson");

                    b.Property<int>("Revision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Drafts", (string)null);
                });

            modelBuilder.Entity("Palantir.Domain.Entities.ExternalIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .HasMaxLength(320);

                    b.Property<bool>("IsLoginEnabled");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(512);

                    b.Property<DateTimeOffset?>("LastVerifiedAt");

                    b.Property<DateTimeOffset>("LinkedAt");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("ProviderSubjectId")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("ProviderTenantId")
                        .HasMaxLength(128);

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Issuer", "ProviderSubjectId")
                        .IsUnique();

                    b.ToTable("ExternalIdentities", (string)null);
                });

            modelBuilder.Entity("Palantir.Domain.Entities.LocalPilotCredential", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<string>("PasswordHash")
                        .IsRequired();

                    b.Property<DateTimeOffset>("UpdatedAt");

                    b.HasKey("UserId");

                    b.ToTable("LocalPilotCredentials", (string)null);
                });

            modelBuilder.Entity("Palantir.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Body");

                    b.Property<Guid?>("ContactId");

                    b.Property<Guid>("ConversationId");

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<bool>("IsInternalNote");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(300);

                    b.Property<string>("ProviderMetadataJson");

                    b.Property<Guid?>("SenderUserId");

                    b.Property<string>("Summary");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("Palantir.Domain.Entities.OAuthGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ConnectedAccountId");

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<string>("CredentialReference")
                        .IsRequired()
                        .HasMaxLength(512);

                    b.Property<DateTimeOffset?>("ExpiresAt");

                    b.Property<DateTimeOffset?>("RevokedAt");

                    b.Property<int>("TokenVersion");

                    b.Property<DateTimeOffset>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ConnectedAccountId");

                    b.ToTable("OAuthGrants", (string)null);
                });

            modelBuilder.Entity("Palantir.Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("Organizations", (string)null);
                });

            modelBuilder.Entity("Palantir.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CustomerId");

                    b.Property<string>("MetadataJson");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<Guid>("OrganizationId");

                    b.Property<Guid?>("OwnerUserId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Palantir.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AssignedToTeamId");

                    b.Property<Guid?>("AssignedToUserId");

                    b.Property<Guid?>("ConversationId");

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<Guid>("CreatedByUserId");

                    b.Property<string>("Description");

                    b.Property<DateTimeOffset?>("DueAt");

                    b.Property<Guid>("OrganizationId");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid?>("ProjectId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("Palantir.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<Guid>("OrganizationId");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("Palantir.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320);

                    b.Property<bool>("IsActive");

                    b.Property<Guid>("OrganizationId");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Email");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Palantir.Domain.Entities.WorkflowAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<Guid?>("ApprovalRequestId");

                    b.Property<Guid?>("ClaimedByConnectorId");

                    b.Property<DateTimeOffset?>("CompletedAt");

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<Guid>("OrganizationId");

                    b.Property<string>("PayloadJson")
                        .IsRequired();

                    b.Property<Guid?>("RequestedByUserId");

                    b.Property<string>("ResultJson");

                    b.Property<DateTimeOffset?>("StartedAt");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("ApprovalRequestId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.HasIndex("RequestedByUserId");

                    b.ToTable("Actions", (string)null);
                });

            modelBuilder.Entity("Palantir.Domain.Entities.ApprovalRequest", b =>
                {
                    b.HasOne("Palantir.Domain.Entities.User", "CompletedByUser")
                        .WithMany()
                        .HasForeignKey("CompletedByUserId");

                    b.HasOne("Palantir.Domain.Entities.Draft", "Draft")
                        .WithMany("ApprovalRequests")
                        .HasForeignKey("DraftId");

                    b.HasOne("Palantir.Domain.Entities.User", "RequestedForUser")
                        .WithMany()
                        .HasForeignKey("RequestedForUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompletedByUser");

                    b.Navigation("Draft");

                    b.Navigation("RequestedForUser");
                });

            modelBuilder.Entity("Palantir.Domain.Entities.AuditEvent", b =>
                {
                    b.HasOne("Palantir.Domain.Entities.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Palantir.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActorUser");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Palantir.Domain.Entities.ConnectedAccount", b =>
                {
                    b.HasOne("Palantir.Domain.Entities.User", "User")
                        .WithMany("ConnectedAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Palantir.Domain.Entities.Connector", b =>
                {
                    b.HasOne("Palantir.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Palantir.Domain.Entities.Contact", b =>
                {
                    b.HasOne("Palantir.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Palantir.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("Palantir.Domain.Entities.Team", "AssignedTeam")
                        .WithMany()
                        .HasForeignKey("AssignedTeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Palantir.Domain.Entities.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Palantir.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("Palantir.Domain.Entities.Organization", "Organization")
                        .WithMany("Conversations")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Palantir.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.Navigation("AssignedTeam");

                    b.Navigation("AssignedUser");

                    b.Navigation("Customer");

                    b.Navigation("Organization");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Palantir.Domain.Entities.Customer", b =>
                {
                    b.HasOne("Palantir.Domain.Entities.Organization", "Organization")
                        .WithMany("Customers")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Palantir.Domain.Entities.Device", b =>
                {
                    b.HasOne("Palantir.Domain.Entities.User", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Palantir.Domain.Entities.Draft", b =>
                {
                    b.HasOne("Palantir.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Drafts")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Palantir.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.Navigation("Conversation");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Palantir.Domain.Entities.ExternalIdentity", b =>
                {
                    b.HasOne("Palantir.Domain.Entities.User", "User")
                        .WithMany("ExternalIdentities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Palantir.Domain.Entities.LocalPilotCredential", b =>
                {
                    b.HasOne("Palantir.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("Palantir.Domain.Entities.LocalPilotCredential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Palantir.Domain.Entities.Message", b =>
                {
                    b.HasOne("Palantir.Domain.Entities.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId");

                    b.HasOne("Palantir.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Palantir.Domain.Entities.User", "SenderUser")
                        .WithMany()
                        .HasForeignKey("SenderUserId");

                    b.Navigation("Contact");

                    b.Navigation("Conversation");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("Palantir.Domain.Entities.OAuthGrant", b =>
                {
                    b.HasOne("Palantir.Domain.Entities.ConnectedAccount", "ConnectedAccount")
                        .WithMany("OAuthGrants")
                        .HasForeignKey("ConnectedAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConnectedAccount");
                });

            modelBuilder.Entity("Palantir.Domain.Entities.Project", b =>
                {
                    b.HasOne("Palantir.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("Palantir.Domain.Entities.Organization", "Organization")
                        .WithMany("Projects")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Palantir.Domain.Entities.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("Organization");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("Palantir.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("Palantir.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Palantir.Domain.Entities.Team", b =>
                {
                    b.HasOne("Palantir.Domain.Entities.Organization", "Organization")
                        .WithMany("Teams")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Palantir.Domain.Entities.User", b =>
                {
                    b.HasOne("Palantir.Domain.Entities.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Palantir.Domain.Entities.WorkflowAction", b =>
                {
                    b.HasOne("Palantir.Domain.Entities.ApprovalRequest", "ApprovalRequest")
                        .WithMany()
                        .HasForeignKey("ApprovalRequestId");

                    b.HasOne("Palantir.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Palantir.Domain.Entities.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId");

                    b.Navigation("ApprovalRequest");

                    b.Navigation("Organization");

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("Palantir.Domain.Entities.ConnectedAccount", b =>
                {
                    b.Navigation("OAuthGrants");
                });

            modelBuilder.Entity("Palantir.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Drafts");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Palantir.Domain.Entities.Draft", b =>
                {
                    b.Navigation("ApprovalRequests");
                });

            modelBuilder.Entity("Palantir.Domain.Entities.Organization", b =>
                {
                    b.Navigation("Conversations");

                    b.Navigation("Customers");

                    b.Navigation("Projects");

                    b.Navigation("Teams");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Palantir.Domain.Entities.User", b =>
                {
                    b.Navigation("ConnectedAccounts");

                    b.Navigation("Devices");

                    b.Navigation("ExternalIdentities");
                });
#pragma warning restore 612, 618
        }
    }
}
