-- Project Palantir Initial Azure SQL Schema Draft
-- This is a planning artifact, not production-ready migration code.

CREATE TABLE Organizations (
    OrganizationId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(200) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Users (
    UserId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    OrganizationId UNIQUEIDENTIFIER NOT NULL REFERENCES Organizations(OrganizationId),
    EntraObjectId NVARCHAR(100) NULL,
    DisplayName NVARCHAR(200) NOT NULL,
    Email NVARCHAR(320) NOT NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Teams (
    TeamId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    OrganizationId UNIQUEIDENTIFIER NOT NULL REFERENCES Organizations(OrganizationId),
    Name NVARCHAR(200) NOT NULL
);

CREATE TABLE Devices (
    DeviceId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(UserId),
    DeviceName NVARCHAR(200) NOT NULL,
    Platform NVARCHAR(50) NOT NULL,
    LastSeenAt DATETIME2 NULL,
    PushToken NVARCHAR(MAX) NULL,
    IsActive BIT NOT NULL DEFAULT 1
);

CREATE TABLE Customers (
    CustomerId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    OrganizationId UNIQUEIDENTIFIER NOT NULL REFERENCES Organizations(OrganizationId),
    Name NVARCHAR(300) NOT NULL,
    MetadataJson NVARCHAR(MAX) NULL
);

CREATE TABLE Contacts (
    ContactId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    OrganizationId UNIQUEIDENTIFIER NOT NULL REFERENCES Organizations(OrganizationId),
    CustomerId UNIQUEIDENTIFIER NULL REFERENCES Customers(CustomerId),
    DisplayName NVARCHAR(300) NOT NULL,
    Email NVARCHAR(320) NULL,
    Phone NVARCHAR(50) NULL,
    MetadataJson NVARCHAR(MAX) NULL
);

CREATE TABLE Projects (
    ProjectId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    OrganizationId UNIQUEIDENTIFIER NOT NULL REFERENCES Organizations(OrganizationId),
    CustomerId UNIQUEIDENTIFIER NULL REFERENCES Customers(CustomerId),
    Name NVARCHAR(300) NOT NULL,
    Status NVARCHAR(50) NOT NULL DEFAULT 'Active',
    OwnerUserId UNIQUEIDENTIFIER NULL REFERENCES Users(UserId),
    MetadataJson NVARCHAR(MAX) NULL
);

CREATE TABLE Conversations (
    ConversationId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    OrganizationId UNIQUEIDENTIFIER NOT NULL REFERENCES Organizations(OrganizationId),
    CustomerId UNIQUEIDENTIFIER NULL REFERENCES Customers(CustomerId),
    ProjectId UNIQUEIDENTIFIER NULL REFERENCES Projects(ProjectId),
    Subject NVARCHAR(500) NULL,
    Channel NVARCHAR(50) NOT NULL,
    Status NVARCHAR(50) NOT NULL DEFAULT 'Open',
    AssignedUserId UNIQUEIDENTIFIER NULL REFERENCES Users(UserId),
    AssignedTeamId UNIQUEIDENTIFIER NULL REFERENCES Teams(TeamId),
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Messages (
    MessageId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    ConversationId UNIQUEIDENTIFIER NOT NULL REFERENCES Conversations(ConversationId),
    Direction NVARCHAR(20) NOT NULL,
    SenderUserId UNIQUEIDENTIFIER NULL REFERENCES Users(UserId),
    ContactId UNIQUEIDENTIFIER NULL REFERENCES Contacts(ContactId),
    Body NVARCHAR(MAX) NULL,
    Summary NVARCHAR(MAX) NULL,
    ProviderMessageId NVARCHAR(300) NULL,
    ProviderMetadataJson NVARCHAR(MAX) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Drafts (
    DraftId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    ConversationId UNIQUEIDENTIFIER NOT NULL REFERENCES Conversations(ConversationId),
    CreatedByUserId UNIQUEIDENTIFIER NULL REFERENCES Users(UserId),
    CreatedByAi BIT NOT NULL DEFAULT 0,
    Body NVARCHAR(MAX) NOT NULL,
    Revision INT NOT NULL DEFAULT 1,
    Status NVARCHAR(50) NOT NULL DEFAULT 'Draft',
    MetadataJson NVARCHAR(MAX) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE ApprovalRequests (
    ApprovalRequestId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    DraftId UNIQUEIDENTIFIER NULL REFERENCES Drafts(DraftId),
    RequestedForUserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(UserId),
    Status NVARCHAR(50) NOT NULL DEFAULT 'Pending',
    RequestedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CompletedAt DATETIME2 NULL,
    CompletedByUserId UNIQUEIDENTIFIER NULL REFERENCES Users(UserId),
    ExpiresAt DATETIME2 NULL,
    DraftRevision INT NULL
);

CREATE TABLE Actions (
    ActionId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    OrganizationId UNIQUEIDENTIFIER NOT NULL REFERENCES Organizations(OrganizationId),
    ActionType NVARCHAR(100) NOT NULL,
    Status NVARCHAR(50) NOT NULL DEFAULT 'Pending',
    RequestedByUserId UNIQUEIDENTIFIER NULL REFERENCES Users(UserId),
    ApprovalRequestId UNIQUEIDENTIFIER NULL REFERENCES ApprovalRequests(ApprovalRequestId),
    ClaimedByConnectorId UNIQUEIDENTIFIER NULL,
    IdempotencyKey NVARCHAR(200) NOT NULL,
    PayloadJson NVARCHAR(MAX) NOT NULL,
    ResultJson NVARCHAR(MAX) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    StartedAt DATETIME2 NULL,
    CompletedAt DATETIME2 NULL
);
CREATE UNIQUE INDEX UX_Actions_IdempotencyKey ON Actions(IdempotencyKey);

CREATE TABLE Tasks (
    TaskId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    OrganizationId UNIQUEIDENTIFIER NOT NULL REFERENCES Organizations(OrganizationId),
    ProjectId UNIQUEIDENTIFIER NULL REFERENCES Projects(ProjectId),
    ConversationId UNIQUEIDENTIFIER NULL REFERENCES Conversations(ConversationId),
    CreatedByUserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(UserId),
    AssignedToUserId UNIQUEIDENTIFIER NULL REFERENCES Users(UserId),
    AssignedToTeamId UNIQUEIDENTIFIER NULL REFERENCES Teams(TeamId),
    Title NVARCHAR(500) NOT NULL,
    Description NVARCHAR(MAX) NULL,
    DueAt DATETIME2 NULL,
    Status NVARCHAR(50) NOT NULL DEFAULT 'Open',
    Priority NVARCHAR(50) NOT NULL DEFAULT 'Normal',
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Connectors (
    ConnectorId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    OrganizationId UNIQUEIDENTIFIER NOT NULL REFERENCES Organizations(OrganizationId),
    UserId UNIQUEIDENTIFIER NULL REFERENCES Users(UserId),
    DeviceId UNIQUEIDENTIFIER NULL REFERENCES Devices(DeviceId),
    ConnectorType NVARCHAR(100) NOT NULL,
    Name NVARCHAR(200) NOT NULL,
    Status NVARCHAR(50) NOT NULL DEFAULT 'Offline',
    CapabilitiesJson NVARCHAR(MAX) NOT NULL,
    LastHeartbeatAt DATETIME2 NULL
);

CREATE TABLE AuditEvents (
    AuditEventId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    OrganizationId UNIQUEIDENTIFIER NOT NULL REFERENCES Organizations(OrganizationId),
    ActorUserId UNIQUEIDENTIFIER NULL REFERENCES Users(UserId),
    EventType NVARCHAR(100) NOT NULL,
    EntityType NVARCHAR(100) NULL,
    EntityId UNIQUEIDENTIFIER NULL,
    DetailsJson NVARCHAR(MAX) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

-- Version 0.2: provider-neutral identity and linked external accounts
CREATE TABLE ExternalIdentities (
    ExternalIdentityId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Provider NVARCHAR(64) NOT NULL,
    Issuer NVARCHAR(512) NOT NULL,
    ProviderTenantId NVARCHAR(128) NULL,
    ProviderSubjectId NVARCHAR(256) NOT NULL,
    Email NVARCHAR(320) NULL,
    IsLoginEnabled BIT NOT NULL DEFAULT 1,
    LinkedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    LastVerifiedAt DATETIME2 NULL,
    CONSTRAINT FK_ExternalIdentities_Users FOREIGN KEY (UserId) REFERENCES Users(UserId),
    CONSTRAINT UQ_ExternalIdentities_IssuerSubject UNIQUE (Issuer, ProviderSubjectId)
);

CREATE TABLE ConnectedAccounts (
    ConnectedAccountId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Provider NVARCHAR(64) NOT NULL,
    ProviderTenantId NVARCHAR(128) NULL,
    ProviderAccountId NVARCHAR(256) NOT NULL,
    DisplayName NVARCHAR(256) NULL,
    PrimaryAddress NVARCHAR(320) NULL,
    ConnectionStatus NVARCHAR(64) NOT NULL DEFAULT 'NotConnected',
    GrantedScopesJson NVARCHAR(MAX) NULL,
    LastSuccessfulSyncAt DATETIME2 NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_ConnectedAccounts_Users FOREIGN KEY (UserId) REFERENCES Users(UserId)
);

CREATE TABLE OAuthGrants (
    OAuthGrantId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    ConnectedAccountId UNIQUEIDENTIFIER NOT NULL,
    CredentialReference NVARCHAR(512) NOT NULL,
    TokenVersion INT NOT NULL DEFAULT 1,
    ExpiresAt DATETIME2 NULL,
    RevokedAt DATETIME2 NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_OAuthGrants_ConnectedAccounts FOREIGN KEY (ConnectedAccountId) REFERENCES ConnectedAccounts(ConnectedAccountId)
);
